title: "The Outriders: MK"
description: >-
  Welcome to the Outriders, a wargaming club serving Milton Keynes and surrounding areas.
baseurl: ""
url: "https://outriders-mk.github.io/"
theme: minima
destination: ./docs
plugins:
  - jekyll-feed
